version: "3"

services:
   db:
     image: mysql:5.7
     networks:
        - keycloak-net
     volumes:
        - db_data:/var/lib/mysql
     restart: always
     environment:
        MYSQL_ROOT_PASSWORD: somewordpress
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
     container_name: wp_db

   wordpress:
     depends_on:
        - db
     image: wordpress:latest
     networks:
        - keycloak-net
     expose:
        - 80
     ports:
        - 8090:80
     restart: always
     environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
     container_name: wp_wordpress
volumes:
  db_data:
    driver: local

networks:
  keycloak-net:
    external:
      name: keycloak-net
